// <auto-generated />
using System;
using Mask_STK.Core.WebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Auto_Intelligent_Wms.Core.Model.Migrations
{
    [DbContext(typeof(Auto_Inteligent_Wms_DbContext))]
    partial class Auto_Inteligent_Wms_DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Auto_Intelligent_Wms.Core.Model.Entities.Area", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("库区编码");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<long>("Creator")
                        .HasColumnType("bigint")
                        .HasComment("创建人");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("库区名称");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("备注");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasComment("状态 1：正常 2：删除");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasComment("更新时间");

                    b.Property<long?>("Updator")
                        .HasColumnType("bigint")
                        .HasComment("更新人");

                    b.Property<string>("WareHouseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("仓库编码");

                    b.Property<long>("WareHouseId")
                        .HasColumnType("bigint")
                        .HasComment("仓库id");

                    b.Property<string>("WareHouseName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("仓库名称");

                    b.HasKey("Id");

                    b.ToTable("Mask_STK_Area", (string)null);

                    b.HasComment("库区");
                });

            modelBuilder.Entity("Auto_Intelligent_Wms.Core.Model.Entities.Castle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("AffiliatedUnit")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("所属单位");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("编码");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<long>("Creator")
                        .HasColumnType("bigint")
                        .HasComment("创建人");

                    b.Property<string>("HasGoods")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("是否有货 Y/N");

                    b.Property<string>("LocationCode")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("存储货位编码");

                    b.Property<long?>("LocationId")
                        .HasColumnType("bigint")
                        .HasComment("存储货位id");

                    b.Property<string>("LocationName")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("存储货位名称");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("名称");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("备注");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasComment("状态 1：正常 2：删除");

                    b.Property<int?>("StorageStatus")
                        .HasColumnType("int")
                        .HasComment("存储状态 不在货位/在货位/任务中");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasComment("类型 ：1、料箱");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasComment("更新时间");

                    b.Property<long?>("Updator")
                        .HasColumnType("bigint")
                        .HasComment("更新人");

                    b.HasKey("Id");

                    b.ToTable("Mask_STK_Castles", (string)null);

                    b.HasComment("货物装载容器");
                });

            modelBuilder.Entity("Auto_Intelligent_Wms.Core.Model.Entities.ExpOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<long>("Creator")
                        .HasColumnType("bigint")
                        .HasComment("创建人");

                    b.Property<DateTime?>("ExpTime")
                        .HasColumnType("datetime2")
                        .HasComment("出库时间");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("出库单号");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasComment("出库单类型");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("备注");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasComment("状态 1：正常 2：删除");

                    b.Property<int>("Step")
                        .HasColumnType("int")
                        .HasComment("出库步骤");

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("供应商编码");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasComment("更新时间");

                    b.Property<long?>("Updator")
                        .HasColumnType("bigint")
                        .HasComment("更新人");

                    b.Property<string>("WareHouseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("仓库编码");

                    b.HasKey("Id");

                    b.ToTable("Mask_STK_ExpOrder", (string)null);

                    b.HasComment("出库单");
                });

            modelBuilder.Entity("Auto_Intelligent_Wms.Core.Model.Entities.ExpOrder_Items", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<decimal>("ActualExpQuantity")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("实际出库货物数量");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("仓储库区位置");

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("批次号");

                    b.Property<string>("CastleCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasComment("Castle编码");

                    b.Property<string>("CastleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Castle类型");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<long>("Creator")
                        .HasColumnType("bigint")
                        .HasComment("创建人");

                    b.Property<long>("ExpOrderId")
                        .HasColumnType("bigint")
                        .HasComment("出库单id");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("仓储货位位置");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("物料编码");

                    b.Property<string>("PassageWayCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("出库口编码");

                    b.Property<decimal>("PlanExpQuantity")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("计划出库货物数量");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("备注");

                    b.Property<string>("ShelfCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("仓储货架位置");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasComment("状态 1：正常 2：删除");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasComment("更新时间");

                    b.Property<long?>("Updator")
                        .HasColumnType("bigint")
                        .HasComment("更新人");

                    b.HasKey("Id");

                    b.ToTable("Mask_STK_ExpOrder_Items", (string)null);

                    b.HasComment("出库单明细");
                });

            modelBuilder.Entity("Auto_Intelligent_Wms.Core.Model.Entities.ImpOrder", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<long>("Creator")
                        .HasColumnType("bigint")
                        .HasComment("创建人");

                    b.Property<DateTime?>("ImpTime")
                        .HasColumnType("datetime2")
                        .HasComment("入库时间");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("入库单号");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasComment("入库单类型");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("备注");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasComment("状态 1：正常 2：删除");

                    b.Property<int>("Step")
                        .HasColumnType("int")
                        .HasComment("入库步骤");

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("供应商编码");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasComment("更新时间");

                    b.Property<long?>("Updator")
                        .HasColumnType("bigint")
                        .HasComment("更新人");

                    b.Property<string>("WareHouseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("仓库编码");

                    b.HasKey("Id");

                    b.ToTable("Mask_STK_ImpOrder", (string)null);

                    b.HasComment("入库单");
                });

            modelBuilder.Entity("Auto_Intelligent_Wms.Core.Model.Entities.ImpOrder_Items", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<decimal>("ActualImpQuantity")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("实际入库货物数量");

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("仓储库区位置");

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("批次号");

                    b.Property<string>("CastleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Castle编码");

                    b.Property<string>("CastleType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Castle类型");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<long>("Creator")
                        .HasColumnType("bigint")
                        .HasComment("创建人");

                    b.Property<long>("ImpOrderId")
                        .HasColumnType("bigint")
                        .HasComment("入库单id");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("仓储货位位置");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("物料编码");

                    b.Property<string>("PassageWayCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("入库口编码");

                    b.Property<decimal>("PlanImpQuantity")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("计划入库货物数量");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("备注");

                    b.Property<string>("ShelfCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("仓储货架位置");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasComment("状态 1：正常 2：删除");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasComment("更新时间");

                    b.Property<long?>("Updator")
                        .HasColumnType("bigint")
                        .HasComment("更新人");

                    b.HasKey("Id");

                    b.ToTable("Mask_STK_ImpOrder_Items", (string)null);

                    b.HasComment("入库单明细");
                });

            modelBuilder.Entity("Auto_Intelligent_Wms.Core.Model.Entities.Location", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("货位编码");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<long>("Creator")
                        .HasColumnType("bigint")
                        .HasComment("创建人");

                    b.Property<int>("ExpLock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment(" 出库锁定标识 0：未锁定 1：已锁定");

                    b.Property<int>("ImpLock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasComment("入库锁定标识 0：未锁定 1：已锁定");

                    b.Property<int>("LColumn")
                        .HasColumnType("int")
                        .HasComment("列");

                    b.Property<int>("LRow")
                        .HasColumnType("int")
                        .HasComment("排");

                    b.Property<int>("Layer")
                        .HasColumnType("int")
                        .HasComment("层");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("货位名称");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("备注");

                    b.Property<int>("RoadWay")
                        .HasColumnType("int")
                        .HasComment("巷道");

                    b.Property<string>("ShelfCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("货架编码");

                    b.Property<long>("ShelfId")
                        .HasColumnType("bigint")
                        .HasComment("货架id");

                    b.Property<string>("ShelfName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("货架名称");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasComment("状态 1：正常 2：删除");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasComment("更新时间");

                    b.Property<long?>("Updator")
                        .HasColumnType("bigint")
                        .HasComment("更新人");

                    b.HasKey("Id");

                    b.ToTable("Mask_STK_Locations", (string)null);

                    b.HasComment("货位");
                });

            modelBuilder.Entity("Auto_Intelligent_Wms.Core.Model.Entities.Material", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("物料编码");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<long>("Creator")
                        .HasColumnType("bigint")
                        .HasComment("创建人");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("物料描述");

                    b.Property<decimal>("MinimumPackagingQuantity")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("最小包装数量");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("物料名称");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment(" 每个/价格");

                    b.Property<string>("PriceUint")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("价格单位");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("基本计量单位数量");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("备注");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasComment("状态 1：正常 2：删除");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasComment("物料类型");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("基本单位");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasComment("更新时间");

                    b.Property<long?>("Updator")
                        .HasColumnType("bigint")
                        .HasComment("更新人");

                    b.Property<DateTime>("ValidityPeriod")
                        .HasColumnType("datetime2")
                        .HasComment("有效期");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasComment("物料等级");

                    b.HasKey("Id");

                    b.ToTable("Mask_STK_Materials", (string)null);

                    b.HasComment("物料");
                });

            modelBuilder.Entity("Auto_Intelligent_Wms.Core.Model.Entities.Material_Supplier_RelationShip", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<long>("Creator")
                        .HasColumnType("bigint")
                        .HasComment("创建人");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("物料编码");

                    b.Property<long>("MaterialId")
                        .HasColumnType("bigint")
                        .HasComment("物料id");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("备注");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasComment("状态 1：正常 2：删除");

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("供应商编码");

                    b.Property<long>("SupplierId")
                        .HasColumnType("bigint")
                        .HasComment("供应商id");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasComment("更新时间");

                    b.Property<long?>("Updator")
                        .HasColumnType("bigint")
                        .HasComment("更新人");

                    b.HasKey("Id");

                    b.ToTable("Mask_STK_Material_Supplier_RelationShips", (string)null);

                    b.HasComment("物料供应商关系");
                });

            modelBuilder.Entity("Auto_Intelligent_Wms.Core.Model.Entities.Operate_Log", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<long>("Creator")
                        .HasColumnType("bigint")
                        .HasComment("创建人");

                    b.Property<string>("ErrorMsg")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("错误消息");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("ip地址");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("方法名称");

                    b.Property<string>("OperateParams")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("参数");

                    b.Property<int>("OperateStatus")
                        .HasColumnType("int")
                        .HasComment("操作状态");

                    b.Property<string>("OperateType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("操作类型");

                    b.Property<string>("OperateUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("操作路径");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("备注");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasComment("状态 1：正常 2：删除");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("标题");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasComment("更新时间");

                    b.Property<long?>("Updator")
                        .HasColumnType("bigint")
                        .HasComment("更新人");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("用户编码");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("用户名称");

                    b.HasKey("Id");

                    b.ToTable("Mask_STK_Operate_Log", (string)null);

                    b.HasComment("操作日志");
                });

            modelBuilder.Entity("Auto_Intelligent_Wms.Core.Model.Entities.PassageWay", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("编码");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<long>("Creator")
                        .HasColumnType("bigint")
                        .HasComment("创建人");

                    b.Property<string>("FirstLanway")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasComment("一号巷道");

                    b.Property<string>("ForthLanway")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasComment("四号巷道");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("名称");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("备注");

                    b.Property<string>("SecondLanway")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasComment("二号巷道");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasComment("状态 1：正常 2：删除");

                    b.Property<string>("ThirdtLanway")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasComment("三号巷道");

                    b.Property<int>("Type")
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .HasComment("通道类型 1：入库口 2：出库口");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasComment("更新时间");

                    b.Property<long?>("Updator")
                        .HasColumnType("bigint")
                        .HasComment("更新人");

                    b.Property<string>("WareHouseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("仓库编码");

                    b.Property<long>("WareHouseId")
                        .HasColumnType("bigint")
                        .HasComment("仓库id");

                    b.Property<string>("WareHouseName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("仓库名称");

                    b.HasKey("Id");

                    b.ToTable("Mask_STK_PassageWay", (string)null);

                    b.HasComment("通道");
                });

            modelBuilder.Entity("Auto_Intelligent_Wms.Core.Model.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("角色编码");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<long>("Creator")
                        .HasColumnType("bigint")
                        .HasComment("创建人");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("角色描述");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("角色名称");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("备注");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasComment("状态 1：正常 2：注销 3.禁用");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasComment("更新时间");

                    b.Property<long?>("Updator")
                        .HasColumnType("bigint")
                        .HasComment("更新人");

                    b.HasKey("Id");

                    b.ToTable("Mask_STK_Roles", (string)null);

                    b.HasComment("角色");
                });

            modelBuilder.Entity("Auto_Intelligent_Wms.Core.Model.Entities.Shelf", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("库区编码");

                    b.Property<long>("AreaId")
                        .HasColumnType("bigint")
                        .HasComment("库区id");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("库区名称");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("货架编码");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<long>("Creator")
                        .HasColumnType("bigint")
                        .HasComment("创建人");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("货架名称");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("备注");

                    b.Property<int>("RoadWay")
                        .HasColumnType("int")
                        .HasComment("巷道数");

                    b.Property<int>("ShelfColumns")
                        .HasColumnType("int")
                        .HasComment("列数");

                    b.Property<int>("ShelfLayers")
                        .HasColumnType("int")
                        .HasComment("层数");

                    b.Property<int>("ShelfRows")
                        .HasColumnType("int")
                        .HasComment("排数");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasComment("状态 1：正常 2：删除");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasComment("更新时间");

                    b.Property<long?>("Updator")
                        .HasColumnType("bigint")
                        .HasComment("更新人");

                    b.HasKey("Id");

                    b.ToTable("Mask_STK_Shelfs", (string)null);

                    b.HasComment("货架");
                });

            modelBuilder.Entity("Auto_Intelligent_Wms.Core.Model.Entities.StockInventory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("库区编码");

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("批次");

                    b.Property<string>("CastleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Castle编码");

                    b.Property<int>("CastleType")
                        .HasColumnType("int")
                        .HasComment("Castle类型");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<long>("Creator")
                        .HasColumnType("bigint")
                        .HasComment("创建人");

                    b.Property<string>("IsFreeze")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasComment("是否冻结 N/Y");

                    b.Property<string>("IsLock")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasComment("是否锁定 N/Y");

                    b.Property<string>("IsOccupy")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasComment("是否占用 N/Y");

                    b.Property<string>("IsScrap")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasComment("是否报废 N/Y");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("物料编码");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("每个/价格");

                    b.Property<string>("PriceUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("价格单位");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("库存数量");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("备注");

                    b.Property<string>("ShelfCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("货架编码");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasComment("状态 1：正常 2：删除");

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("供应商编码");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("基本单位");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasComment("更新时间");

                    b.Property<long?>("Updator")
                        .HasColumnType("bigint")
                        .HasComment("更新人");

                    b.Property<DateTime>("ValidityPeriod")
                        .HasColumnType("datetime2")
                        .HasComment("有效期");

                    b.Property<string>("Version")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("物料等级");

                    b.Property<string>("WareHouseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("仓库编码");

                    b.HasKey("Id");

                    b.ToTable("Mask_STK_StockInventory", (string)null);

                    b.HasComment("库存明细");
                });

            modelBuilder.Entity("Auto_Intelligent_Wms.Core.Model.Entities.StockInventory_History", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("库区编码");

                    b.Property<string>("BatchNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("批次");

                    b.Property<string>("CastleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Castle编码");

                    b.Property<int>("CastleType")
                        .HasColumnType("int")
                        .HasComment("Castle类型");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<long>("Creator")
                        .HasColumnType("bigint")
                        .HasComment("创建人");

                    b.Property<string>("IsFreeze")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasComment("是否冻结 N/Y");

                    b.Property<string>("IsLock")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasComment("是否锁定 N/Y");

                    b.Property<string>("IsOccupy")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasComment("是否占用 N/Y");

                    b.Property<string>("IsScrap")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasComment("是否报废 N/Y");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("物料编码");

                    b.Property<decimal>("OperateQuantity")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("操作库存数量");

                    b.Property<int>("OperateType")
                        .HasColumnType("int")
                        .HasComment("操作类型");

                    b.Property<string>("OperateTypeDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasComment("操作类型描述");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasComment("订单类型");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("每个/价格");

                    b.Property<string>("PriceUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("价格单位");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("库存数量");

                    b.Property<string>("RelatedOrder")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("关联单号");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("备注");

                    b.Property<string>("ShelfCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("货架编码");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasComment("状态 1：正常 2：删除");

                    b.Property<string>("SupplierCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("供应商编码");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("基本单位");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasComment("更新时间");

                    b.Property<long?>("Updator")
                        .HasColumnType("bigint")
                        .HasComment("更新人");

                    b.Property<DateTime>("ValidityPeriod")
                        .HasColumnType("datetime2")
                        .HasComment("有效期");

                    b.Property<string>("Version")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("物料等级");

                    b.Property<string>("WareHouseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("仓库编码");

                    b.HasKey("Id");

                    b.ToTable("Mask_STK_StockInventory_History", (string)null);

                    b.HasComment("库存明细历史记录");
                });

            modelBuilder.Entity("Auto_Intelligent_Wms.Core.Model.Entities.Supplier", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("居住地址");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("供应商编码");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<long>("Creator")
                        .HasColumnType("bigint")
                        .HasComment("创建人");

                    b.Property<string>("Email")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("电子邮件");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("供应商名称");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("备注");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasComment("状态 1：正常 2：注销 3.禁用");

                    b.Property<string>("Telephone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("联系电话");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasComment("更新时间");

                    b.Property<long?>("Updator")
                        .HasColumnType("bigint")
                        .HasComment("更新人");

                    b.HasKey("Id");

                    b.ToTable("Mask_STK_Suppliers", (string)null);

                    b.HasComment("供应商");
                });

            modelBuilder.Entity("Auto_Intelligent_Wms.Core.Model.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("居住地址");

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasComment("年龄");

                    b.Property<string>("Birth")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("出生年月份");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("用户编码");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<long>("Creator")
                        .HasColumnType("bigint")
                        .HasComment("创建人");

                    b.Property<string>("Email")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("电子邮件");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasComment("性别(M:男生 W：女生)");

                    b.Property<long?>("JWTVersion")
                        .HasColumnType("bigint")
                        .HasComment("自增jwt令牌");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("用户姓名");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("密码");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("联系电话");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("备注");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasComment("状态 1：正常 2：注销 3.禁用");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasComment("更新时间");

                    b.Property<long?>("Updator")
                        .HasColumnType("bigint")
                        .HasComment("更新人");

                    b.HasKey("Id");

                    b.ToTable("Mask_STK_Users", (string)null);

                    b.HasComment("用户");
                });

            modelBuilder.Entity("Auto_Intelligent_Wms.Core.Model.Entities.User_Role_RelationShip", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<long>("Creator")
                        .HasColumnType("bigint")
                        .HasComment("创建人");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("备注");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("角色编码");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasComment("角色id");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("角色名称");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasComment("状态 1：正常 2：删除");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasComment("更新时间");

                    b.Property<long?>("Updator")
                        .HasColumnType("bigint")
                        .HasComment("更新人");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("用户编码");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasComment("用户id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("用户名称");

                    b.HasKey("Id");

                    b.ToTable("Mask_STK_User_Role_RelationShips", (string)null);

                    b.HasComment("用户角色关系");
                });

            modelBuilder.Entity("Auto_Intelligent_Wms.Core.Model.Entities.WareHouse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("仓库编码");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasComment("创建时间");

                    b.Property<long>("Creator")
                        .HasColumnType("bigint")
                        .HasComment("创建人");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasComment("仓库名称");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("备注");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasComment("状态 1：正常 2：删除");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)")
                        .HasComment("仓库类型");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("datetime2")
                        .HasComment("更新时间");

                    b.Property<long?>("Updator")
                        .HasColumnType("bigint")
                        .HasComment("更新人");

                    b.HasKey("Id");

                    b.ToTable("Mask_STK_WareHouses", (string)null);

                    b.HasComment("仓库");
                });
#pragma warning restore 612, 618
        }
    }
}
